base:
  project: Diabetes-prediction
  random_state: 42
  target_col: Outcome

data_source:
  s3_source: data_given/kaggle_diabetes.csv

load_data:
  raw_dataset_csv: data/raw/kaggle_diabetes.csv

split_data:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  test_size: 0.2

estimators:
  RandomforestClassifier:
    params:
      n_estimators: 37
model_dir: models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib